package com.production.app.dto;

import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * ============================================================
 * RESPONSE DTO — ProductResponseDTO
 * ============================================================
 *
 * This is what the API returns to the client.
 * It is deliberately different from both the entity and the
 * request DTO:
 *
 *   - Includes server-generated fields (id, createdAt, updatedAt)
 *     that clients cannot set but should see in responses.
 *   - Can be enriched with computed fields (e.g., "inStock" boolean
 *     derived from stockQuantity > 0) without touching the entity.
 *   - Allows the API contract to evolve independently of the DB schema.
 *
 * IMMUTABILITY NOTE:
 *   Response DTOs are ideally immutable (no setters). Using @Value
 *   from Lombok would enforce this. We use @Data here for simplicity
 *   but in a strict architecture, @Value + @Builder is preferred.
 *
 * Jackson (the JSON serializer included in spring-boot-starter-web)
 * uses the getters generated by @Data to serialize this to JSON.
 * Field names become JSON keys by default (camelCase).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ProductResponseDTO {

    private Long id;
    private String sku;
    private String name;
    private String description;
    private BigDecimal price;
    private Integer stockQuantity;
    private String category;

    /**
     * Computed field — not stored in DB, derived from stockQuantity.
     * This is a key benefit of DTOs: you can add presentation-layer
     * logic without polluting the entity.
     */
    private Boolean inStock;

    private Boolean active;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
